language: java
jdk:
  - openjdk11
script: env && ./mvnw package -B

# push to CF
deploy:
  provider: cloudfoundry
  username: aerinle@pivotal.io
  password: test
  api: https://api.run.pivotal.io
  organization: Federal
  space: Bayo
  manifest: manifest-v1.yml
